### ISSUE TITLE
java error when trying to add a git repo 

### ISSUE THREAD

**Issue by asciibene** [orgzly-revived/orgzly-android-revived#243]
Device: java.io.IOException: fc.z: github.com:asciibene/orgmode.git: remote hung up unexpectedly
	at w5.f.l(GitRepo.java:60)
	at w5.f.o(GitRepo.java:3)
	at w5.f.p(GitRepo.java:18)
	at com.orgzly.android.ui.repo.git.GitRepoActivity$d.c(GitRepoActivity.kt:9)
	at com.orgzly.android.ui.repo.git.GitRepoActivity$d.doInBackground(GitRepoActivity.kt:3)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: fc.z: github.com:asciibene/orgmode.git: remote hung up unexpectedly
	at ec.l.k(FetchCommand.java:137)
	at ec.h.r(CloneCommand.java:113)
	at ec.h.m(CloneCommand.java:37)
	at w5.f.l(GitRepo.java:39)
	... 10 more
Caused by: jc.r0: github.com:asciibene/orgmode.git: remote hung up unexpectedly
	at ld.r3$d.<init>(TransportGitSsh.java:32)
	at ld.r3.h0(TransportGitSsh.java:3)
	at ld.i0.h(FetchProcess.java:61)
	at ld.i0.g(FetchProcess.java:24)
	at ld.n3.j(Transport.java:104)
	at ec.l.k(FetchCommand.java:55)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/management/ReflectionException;
	at lb.e.b(ExceptionUtils.java:51)
	at wa.c.w6(AbstractSshFuture.java:34)
	at v9.e.C6(DefaultAuthFuture.java:3)
	at v9.e.r3(DefaultAuthFuture.java:1)
	at wa.m.b(VerifiableFuture.java:7)
	at wa.i.W5(DefaultVerifiableSshFuture.java:1)
	at od.m.k(SshdSession.java:136)
	at od.m.m(SshdSession.java:29)
	at od.f0.X(SshdSessionFactory.java:28)
	at od.f0.d(SshdSessionFactory.java:1)
	at ld.h3.K0(SshTransport.java:41)
	at ld.r3$d.<init>(TransportGitSsh.java:4)
	... 18 more
Caused by: java.lang.ClassNotFoundException: javax.management.ReflectionException
	... 30 more

    Android Version: 11
    Orgzly Revived Version: latest
    Repository type(s) used: github

**Comment by amberin** [comment]
When you see the cause "remote hung up unexpectedly" it is usually not a problem in Orgzly. Please verify the following:
- the SSH key has been authorized
- you have accepted the server's public key in the notification prompt that appears upon first connection
- the URL you are using works from another device
- the "unlock SSH key" prompt was shown if your key is protected by device lock

**Comment by amberin** [comment]
On Android 14 (and probably on 13, too), the "accept server public key" notification currently cannot be shown unless the user has explicitly granted Orgzly permission to show notifications. I didn't think of this notification when I worked on #241. I hope to have a fix soon.

**Comment by asciibene** [comment]
Verified all that already im puzzled

**Comment by amberin** [comment]
Sounds frustrating, but unfortunately there are many possible error sources. Access to the server logs helps a lot, but I noticed it's Github, so that's out of the question. :/
