### ISSUE TITLE
java.lang.NullPointerException: getCurrentActivity() must not be null

### ISSUE THREAD

**Issue by licaon-kter** [orgzly-revived/orgzly-android-revived#274]
1.8.22 random crash
```
java.lang.NullPointerException: getCurrentActivity() must not be null
	at v5.j.d(RemindersScheduler.kt:19)
	at v5.j.h(RemindersScheduler.kt:10)
	at com.orgzly.android.reminders.RemindersBroadcastReceiver.i(RemindersBroadcastReceiver.kt:164)
	at com.orgzly.android.reminders.RemindersBroadcastReceiver.b(RemindersBroadcastReceiver.kt:1)
	at com.orgzly.android.reminders.RemindersBroadcastReceiver$b.s(RemindersBroadcastReceiver.kt:142)
	at com.orgzly.android.reminders.RemindersBroadcastReceiver$b.C(RemindersBroadcastReceiver.kt:9)
	at com.orgzly.android.reminders.RemindersBroadcastReceiver$b.b(RemindersBroadcastReceiver.kt:3)
	at e7.d$a.s(BroadcastReceiverExt.kt:33)
	at z7.a.j(ContinuationImpl.kt:12)
	at o8.s0.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.scheduling.a.q(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.a$c.d(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.a$c.n(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.a$c.run(CoroutineScheduler.kt:1)
	Suppressed: o8.q0: [f2{Cancelling}@afd3a15, Dispatchers.Default]
```

**Comment by amberin** [comment]
Thank you very much -- it looks like I created a nasty bug in 67ccf2fe. I wonder if this is related to #270.

**Comment by licaon-kter** [comment]
Note that I don't use the widget, nor have I interacted directly with Orgzly at that time. The crash just poped up.

**Comment by amberin** [comment]
Thanks, that's very useful. And it makes sense, because Orgzly may try to schedule reminders when it has no Activity, and that's when we hit this bug. It should be trivial to fix, but I'm trying to think of a good regression test, and that's a bit harder.
