### ISSUE TITLE
"Problem loading widget": Saved searches widget doesn't load

### ISSUE THREAD

**Issue by hylophile** [orgzly-revived/orgzly-android-revived#382]
- I have searched for existing issues that may be the same as or related to mine.

Please complete the following information:

    Device: Pixel 3a
    Android Version: 12
    Orgzly Revived Version: 1.8.28 (fdroid)
    Sync repository type (directory/Dropbox/WebDAV/Git): directory

Hi,

as of today (as far as I've noticed), the Saved Searches widget stopped working. It only shows "Problem loading widget".
I've already tried clearing the database (and clearing all storage & cache of the app), but the widget also doesn't load then. I installed Orgzly Revived only recently, and the widget did work for a while.

I checked `adb logcat | grep -i orgzly` after a system restart and spotted these logs which look related:
```log
10-22 21:25:00.647  3550  3550 W AppWidgetHostView: android.view.InflateException: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Error inflating class TextView
10-22 21:25:00.647  3550  3550 W AppWidgetHostView: Caused by: android.view.InflateException: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Error inflating class TextView
10-22 21:25:16.552  1779  3901 I ActivityManager: Killing 3523:com.orgzlyrevived/u0a544 (adj 975): empty #33 
```

Unfortunately that's as far as my Android debugging expertise goes (as of now). I'm happy to give any further information though.

Update: The widget works fine when I downgrade to 1.8.27, and breaks again when I upgrade back to 1.8.28.

**Comment by amberin** [comment]
Thank you very much for reporting this. The widget is very hard to test in an automated way. Clearly, one of the dependency updates in 1.8.28 broke it on your device, while it works fine on my Pixel 5 with Android 14.... Sigh. I wonder what is happening, and how to catch something like this.

I'll try to reproduce the problem on a virtual device. Meanwhile, I recommend you stay on 1.8.27.

**Comment by hylophile** [comment]
Thanks amberin! (And on that occasion, thanks for maintaining this app!)

I dug a bit deeper into this (by running the app from a fresh clone and with Android Studio. Just in case someone else is running into it: For me, the widget loads up fine when using the default Pixel Launcher. The error only happens when using **Lawnchair** as a launcher (and with 1.8.28). I noticed this thanks to more elaborate logs in Android Studio:

```log
2024-10-29 16:10:57.275  3550-3550  AppWidgetHostView       ch.deletescape.lawnchair.plah        W  Error inflating RemoteViews
                                                                                                    android.view.InflateException: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Error inflating class TextView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #53 in com.orgzlyrevived:layout/list_widget: Error inflating class TextView
                                                                                                    Caused by: java.lang.NumberFormatException: For input string: "@2131952570"
                                                                                                    	at java.lang.Integer.parseInt(Integer.java:790)
                                                                                                    	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:347)
                                                                                                    	at android.content.res.TypedArray.getInt(TypedArray.java:435)
                                                                                                    	at ch.deletescape.lawnchair.font.CustomFontManager.loadCustomFont(CustomFontManager.kt:4)
                                                                                                    	at ch.deletescape.lawnchair.LawnchairLayoutInflater.onViewCreated(LawnchairLayoutInflater.kt:3)
                                                                                                    	at ch.deletescape.lawnchair.LawnchairLayoutInflater.onCreateView(LawnchairLayoutInflater.kt:2)
                                                                                                    	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at ch.deletescape.lawnchair.LawnchairLayoutInflater.inflate(LawnchairLayoutInflater.kt:1)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at android.widget.RemoteViews.inflateView(RemoteViews.java:5596)
                                                                                                    	at android.widget.RemoteViews.access$3500(RemoteViews.java:169)
                                                                                                    	at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:5723)
                                                                                                    	at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:5682)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

I'm not sure how to debug this further, but happy to try suggestions/tips. It's unfortunate that my Orgzly settings are reset again now, I hope there's some way to prevent that when debugging with Android Studio.

**Comment by hylophile** [comment]
Alright, I noticed that the Lawnchair version on the Play Store is around 4 years old and doesn't seem to get updated currently. I installed the newest beta from https://github.com/LawnchairLauncher/lawnchair/releases on my phone, and the widget works fine there.

Personally this issue is resolved for me, feel free to close it!

**Comment by amberin** [comment]
That's great news! Closing this.
